version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 5

  smtp:
    image: bytemark/smtp
    ports:
      - "25:25"

  memcached:
    image: docker.io/bitnami/memcached:1
    ports:
      - '11211:11211'
